---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: surrealist-tls
  namespace: techietenka
spec:
  secretName: surrealist-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - surrealist.techietenka.com

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: surrealdb-tls
  namespace: techietenka
spec:
  secretName: surrealdb-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - surrealdb.techietenka.com

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-tls
  namespace: techietenka
spec:
  secretName: api-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
  dnsNames:
    - api.techietenka.com
