---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surrealist-ingress
  namespace: techietenka
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.priority: "1"
    traefik.ingress.kubernetes.io/router.middlewares: "techietenka-surrealist-ipallowlist@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: surrealist.techietenka.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: surrealist
                port:
                  number: 8080
  tls:
    - hosts:
      - surrealist.techietenka.com
      secretName: surrealist-tls-secret

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surrealdb-ingress
  namespace: techietenka
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.priority: "1"
    traefik.ingress.kubernetes.io/router.middlewares: "techietenka-surrealist-ipallowlist@kubernetescrd,techietenka-strip-acl@kubernetescrd,techietenka-strip-files@kubernetescrd,techietenka-strip-shared@kubernetescrd,techietenka-strip-email@kubernetescrd,techietenka-strip-payments@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: surrealdb.techietenka.com
      http:
        paths:
          - path: /acl
            pathType: Prefix
            backend:
              service:
                name: acl-db-external
                port:
                  number: 8000

          - path: /files
            pathType: Prefix
            backend:
              service:
                name: files-db-external
                port:
                  number: 8000

          - path: /shared
            pathType: Prefix
            backend:
              service:
                name: shared-db-external
                port:
                  number: 8000

          - path: /email
            pathType: Prefix
            backend:
              service:
                name: email-db-external
                port:
                  number: 8000

          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payments-db-external
                port:
                  number: 8000
  tls:
    - hosts:
      - surrealdb.techietenka.com
      secretName: surrealdb-tls-secret
